### ISSUE TITLE
The font size of Abstract's Title should be 'small two'

### ISSUE THREAD

**Issue by Ash-Zheng** [ganler/overleaf_tongji_thesis#1]

**Comment by ganler** [comment]
1. Add the following line onto styledef.tex

\newcommand{\xiaoer}{\fontsize{18pt}{18pt}\selectfont}

2. Replace '/zihao{5}' to 'xiaoer' in section/abstract (both on zh/eng versions)

I will create a pull request regarding the change. Thank you.
